function hdr = define_avwhdr()
% function define_avwhdr()
% creates a structure with a blank analyze header'
hdr = struct(...
      'sizeof_hdr'      , 348, ...
      'pad1'            , char(zeros(28,1)), ...
      'extents'         , 0 , ...
      'pad2'            , char(zeros(2,1)), ...
      'regular'         , ' ', ...
      'pad3'            , ' ',...
      'dims'            , 0, ...
      'xdim'            , 0, ...
      'ydim'            , 0, ...
      'zdim'            , 0, ...
      'tdim'            , 0, ...
      'pad4'            , char(zeros(20,1)),...
      'datatype'        , 0, ...
      'bits'            , 0, ...
      'pad5'            , char(zeros(6,1)),...
      'xsize'           , 0, ...
      'ysize'           , 0, ...
      'zsize'           , 0, ...
      'pad6'            , char(zeros(48,1)) ,...
      'glmax'           , 0, ...
      'glmin'           , 0, ...
      'descrip'         , char(zeros(80,1)),...
      'aux_file'        , char(zeros(24,1)),...
      'orient'          , ' ', ...
      'origin'          , zeros(5,1),...
      'generated'       , char(zeros(10,1)),...
      'scannum'         , char(zeros(10,1)),...
      'patient_id'      , char(zeros(10,1)),...
      'exp_date'        , char(zeros(10,1)),...
      'exp_time'        , char(zeros(10,1)),...
      'hist_un0'        , char(zeros(3,1)),...
      'views'           , 0, ...
      'vols_added'      , 0, ...
      'start_field'     , 0, ...
      'field_skip'      , 0, ...
      'omax'            , 0, ...
      'omin'            , 0, ...
      'smax'            , 0,...
      'smin'            , 0 ...
      );

return
