function hdr = make_hdr(slices)
% Creates Analyze header structure from slices structure array

pad1(1:28) = char(0);
pad2(1:2) = char(0);
pad4(1:20) = char(0);
pad5(1:6) = char(0);
pad6(1:120) = char(0);
descrip(1:120) = char(0);

hdr = struct(...
      'sizeof_hdr', 348,...
      'pad1', pad1,...
      'extents', 0,...
      'pad2', pad2,...
      'regular','r', ...
      'pad3', ' ',...
      'dims', 3,...
      'xdim', slices(1).xdim,...
      'ydim', slices(1).ydim,...
      'zdim', slices(1).n_slices,...
      'tdim', 1,...
      'pad4', pad4,...
      'datatype', 4,...   %(short int)
      'bits', 16,...
      'pad5', pad5,...
      'xsize', slices(1).pix_mm,...
      'ysize', slices(1).pix_mm,...
      'zsize', slices(1).slice_mm,...
      'glmax', 0,...
      'glmin', 0,... 
      'descrip', descrip,...
      'pad6', pad6...
      );

return
